#!/bin/bash
set -e
case "$1" in
    remove|upgrade|deconfigure)
        systemctl stop clixon-vpp-restconf 2>/dev/null || true
        systemctl stop clixon-vpp-backend 2>/dev/null || true
        systemctl disable clixon-vpp-restconf 2>/dev/null || true
        systemctl disable clixon-vpp-backend 2>/dev/null || true
        ;;
esac
exit 0
